import {
    hIcon3,
    uIcon3,
    vIcon3,
    wIcon3,
    xIcon1,
    xIcon10,
    xIcon11,
    xIcon12,
    xIcon2,
    xIcon3,
    xIcon4,
    xIcon5,
    xIcon6,
    xIcon7,
    xIcon8,
    xIcon9,
    yIcon1,
    yIcon10,
    yIcon11,
    yIcon12,
    yIcon2,
    yIcon3,
    yIcon4,
    yIcon5,
    yIcon6,
    yIcon7,
    yIcon8,
    yIcon9,
    zIcon1,
    zIcon10,
    zIcon11,
    zIcon12,
    zIcon2,
    zIcon3,
    zIcon4,
    zIcon5,
    zIcon6,
    zIcon7,
    zIcon8,
    zIcon9
} from './variableIcons'
import {
    axesCubeFilledIcon,
    axesCubeIcon,
    axesSphereFilledIcon,
    axesSphereIcon,
    axesTetrahedronFilledIcon,
    axesTetrahedronIcon,
    axesXYZIcon,
} from './axesIcons'
import {
    shape3dAbstract1Icon,
    shape3dAbstract2Icon,
    shape3dAbstract3Icon,
    shape3dAbstractFilled1Icon,
    shape3dAbstractFilled2Icon,
    shape3dAbstractFilled3Icon,
    shape3dHexagon1Icon,
    shape3dHexagonFilled1Icon,
    shape3dMultiplicationFilledIcon,
    shape3dMultiplicationIcon,
    shape3dPentagon1Icon,
    shape3dPentagonFilled1Icon,
    shape3dPlusFilledIcon,
    shape3dPlusIcon,
    shape3dShapesIcon,
    shape3dStar1Icon,
    shape3dStarFilled1Icon,
    shapeAxesCubeFilledIcon,
    shapeAxesCubeIcon,
    shapeAxesPyramidFilledIcon,
    shapeAxesPyramidIcon,
    shapeAxesSphereFilledIcon,
    shapeAxesSphereIcon,
    shapeCone1Icon,
    shapeCone2Icon,
    shapeConeFilled1Icon,
    shapeConeFilled2Icon,
    shapeCube1Icon,
    shapeCubeCut1Icon,
    shapeCubeCut2Icon,
    shapeCubeCutFilled1Icon,
    shapeCubeCutFilled2Icon,
    shapeCubeFilled1Icon,
    shapeCubeTransparentFilledIcon,
    shapeCubeTransparentIcon,
    shapeCuboid1Icon,
    shapeCuboidFilled1Icon,
    shapeCylinder1Icon,
    shapeCylinder2Icon,
    shapeCylinderFilled1Icon,
    shapeCylinderFilled2Icon,
    shapeCylinderSkewedFilledIcon,
    shapeCylinderSkewedIcon,
    shapeCylinderSteps1Icon,
    shapeCylinderStepsFilled1Icon,
    shapeCylinderTransparentFilledIcon,
    shapeCylinderTransparentIcon,
    shapeDiamond1Icon,
    shapeDiamond2Icon,
    shapeDiamond3Icon,
    shapeDiamondFilled1Icon,
    shapeDiamondFilled2Icon,
    shapeDiamondFilled3Icon,
    shapeDodecahedronFilledIcon,
    shapeDodecahedronIcon,
    shapeHorseshoe1Icon,
    shapeHorseshoe2Icon,
    shapeHorseshoeFilled1Icon,
    shapeHorseshoeFilled2Icon,
    shapeHourglass1Icon,
    shapeHourglass2Icon,
    shapeHourglassFilled1Icon,
    shapeHourglassFilled2Icon,
    shapeOctahedronTransparentFilledIcon,
    shapeOctahedronTransparentIcon,
    shapePyramid1Icon,
    shapePyramid2Icon,
    shapePyramid3Icon,
    shapePyramid4Icon,
    shapePyramid5Icon,
    shapePyramidFilled1Icon,
    shapePyramidFilled2Icon,
    shapePyramidFilled3Icon,
    shapePyramidFilled4Icon,
    shapePyramidFilled5Icon,
    shapePyramidTransparentFilledIcon,
    shapePyramidTransparentIcon,
    shapeRhombus1Icon,
    shapeRhombusFilled1Icon,
    shapeSphere1Icon,
    shapeSphere2Icon,
    shapeSphereCut1Icon,
    shapeSphereCutFilled1Icon,
    shapeSphereFilled1Icon,
    shapeSphereFilled2Icon,
    shapeSphereMultiFilledIcon,
    shapeSphereMultiIcon,
    shapeSphereSkewedFilledIcon,
    shapeSphereSkewedIcon,
    shapeSphereTransparentFilledIcon,
    shapeSphereTransparentIcon,
    shapeStepsFilledIcon,
    shapeStepsIcon,
    shapeTorusFilledIcon,
    shapeTorusIcon,
    shapeTrapezium1Icon,
    shapeTrapezium2Icon,
    shapeTrapeziumFilled1Icon,
    shapeTrapeziumFilled2Icon
} from './shapesIcons'
import {HTMLAttributes, ReactElement} from 'react'

const monoIcon = (icon: (props: HTMLAttributes<SVGElement>)=>ReactElement)=>(props?: HTMLAttributes<SVGElement>)=>icon({...props, className: 'bpIconWrapperMonoFilter' + (props?.className||'')})

export const bpUiConfigIcons = {
    'x-1': xIcon1,
    'y-1': yIcon1,
    'z-1': zIcon1,
    'x-2': xIcon2,
    'y-2': yIcon2,
    'z-2': zIcon2,
    'x-3': xIcon3,
    'y-3': yIcon3,
    'z-3': zIcon3,
    'u-3': uIcon3,
    'v-3': vIcon3,
    'w-3': wIcon3,
    'h-3': hIcon3,
    'x-4': xIcon4,
    'y-4': yIcon4,
    'z-4': zIcon4,
    'x-5': xIcon5,
    'y-5': yIcon5,
    'z-5': zIcon5,
    'x-6': xIcon6,
    'y-6': yIcon6,
    'z-6': zIcon6,
    'x-7': xIcon7,
    'y-7': yIcon7,
    'z-7': zIcon7,
    'x-8': xIcon8,
    'y-8': yIcon8,
    'z-8': zIcon8,
    'x-9': xIcon9,
    'y-9': yIcon9,
    'z-9': zIcon9,
    'x-10': xIcon10,
    'y-10': yIcon10,
    'z-10': zIcon10,
    'x-11': xIcon11,
    'y-11': yIcon11,
    'z-11': zIcon11,
    'x-12': xIcon12,
    'y-12': yIcon12,
    'z-12': zIcon12,
    'axes-xyz': axesXYZIcon,
    'axes-cube': axesCubeIcon,
    'axes-tetrahedron': axesTetrahedronIcon,
    'axes-sphere': axesSphereIcon,
    'axes-cube-filled': axesCubeFilledIcon,
    'axes-tetrahedron-filled': axesTetrahedronFilledIcon,
    'axes-sphere-filled': axesSphereFilledIcon,

    'shape-cone-filled-1': shapeConeFilled1Icon,
    'shape-cone-filled-mono-1': monoIcon(shapeConeFilled1Icon),
    'shape-cone-1': shapeCone1Icon,
    'shape-sphere-filled-1': shapeSphereFilled1Icon,
    'shape-sphere-filled-mono-1': monoIcon(shapeSphereFilled1Icon),
    'shape-sphere-1': shapeSphere1Icon,
    'shape-cube-filled-1': shapeCubeFilled1Icon,
    'shape-cube-filled-mono-1': monoIcon(shapeCubeFilled1Icon),
    'shape-cube-1': shapeCube1Icon,
    'shape-cylinder-filled-1': shapeCylinderFilled1Icon,
    'shape-cylinder-filled-mono-1': monoIcon(shapeCylinderFilled1Icon),
    'shape-cylinder-1': shapeCylinder1Icon,
    'shape-pyramid-filled-1': shapePyramidFilled1Icon,
    'shape-pyramid-filled-mono-1': monoIcon(shapePyramidFilled1Icon),
    'shape-pyramid-1': shapePyramid1Icon,
    'shape-rhombus-filled-1': shapeRhombusFilled1Icon,
    'shape-rhombus-filled-mono-1': monoIcon(shapeRhombusFilled1Icon),
    'shape-rhombus-1': shapeRhombus1Icon,
    'shape-3d-hexagon-filled-1': shape3dHexagonFilled1Icon,
    'shape-3d-hexagon-filled-mono-1': monoIcon(shape3dHexagonFilled1Icon),
    'shape-3d-hexagon-1': shape3dHexagon1Icon,
    'shape-pyramid-filled-2': shapePyramidFilled2Icon,
    'shape-pyramid-filled-mono-2': monoIcon(shapePyramidFilled2Icon),
    'shape-pyramid-2': shapePyramid2Icon,
    'shape-3d-star-filled-1': shape3dStarFilled1Icon,
    'shape-3d-star-filled-mono-1': monoIcon(shape3dStarFilled1Icon),
    'shape-3d-star-1': shape3dStar1Icon,
    'shape-cuboid-filled-1': shapeCuboidFilled1Icon,
    'shape-cuboid-filled-mono-1': monoIcon(shapeCuboidFilled1Icon),
    'shape-cuboid-1': shapeCuboid1Icon,
    'shape-cylinder-steps-filled-1': shapeCylinderStepsFilled1Icon,
    'shape-cylinder-steps-filled-mono-1': monoIcon(shapeCylinderStepsFilled1Icon),
    'shape-cylinder-steps-1': shapeCylinderSteps1Icon,
    'shape-trapezium-filled-1': shapeTrapeziumFilled1Icon,
    'shape-trapezium-filled-mono-1': monoIcon(shapeTrapeziumFilled1Icon),
    'shape-trapezium-1': shapeTrapezium1Icon,
    'shape-sphere-cut-filled-1': shapeSphereCutFilled1Icon,
    'shape-sphere-cut-filled-mono-1': monoIcon(shapeSphereCutFilled1Icon),
    'shape-sphere-cut-1': shapeSphereCut1Icon,
    'shape-trapezium-filled-2': shapeTrapeziumFilled2Icon,
    'shape-trapezium-filled-mono-2': monoIcon(shapeTrapeziumFilled2Icon),
    'shape-trapezium-2': shapeTrapezium2Icon,
    'shape-pyramid-filled-3': shapePyramidFilled3Icon,
    'shape-pyramid-filled-mono-3': monoIcon(shapePyramidFilled3Icon),
    'shape-pyramid-3': shapePyramid3Icon,
    'shape-hourglass-filled-1': shapeHourglassFilled1Icon,
    'shape-hourglass-filled-mono-1': monoIcon(shapeHourglassFilled1Icon),
    'shape-hourglass-1': shapeHourglass1Icon,
    'shape-cube-cut-filled-1': shapeCubeCutFilled1Icon,
    'shape-cube-cut-filled-mono-1': monoIcon(shapeCubeCutFilled1Icon),
    'shape-cube-cut-1': shapeCubeCut1Icon,
    'shape-torus-filled': shapeTorusFilledIcon,
    'shape-torus-filled-mono': monoIcon(shapeTorusFilledIcon),
    'shape-torus': shapeTorusIcon,
    'shape-3d-abstract-filled-1': shape3dAbstractFilled1Icon,
    'shape-3d-abstract-filled-mono-1': monoIcon(shape3dAbstractFilled1Icon),
    'shape-3d-abstract-1': shape3dAbstract1Icon,
    'shape-cylinder-filled-2': shapeCylinderFilled2Icon,
    'shape-cylinder-filled-mono-2': monoIcon(shapeCylinderFilled2Icon),
    'shape-cylinder-2': shapeCylinder2Icon,
    'shape-3d-pentagon-filled-1': shape3dPentagonFilled1Icon,
    'shape-3d-pentagon-filled-mono-1': monoIcon(shape3dPentagonFilled1Icon),
    'shape-3d-pentagon-1': shape3dPentagon1Icon,
    'shape-horseshoe-filled-1': shapeHorseshoeFilled1Icon,
    'shape-horseshoe-filled-mono-1': monoIcon(shapeHorseshoeFilled1Icon),
    'shape-horseshoe-1': shapeHorseshoe1Icon,
    'shape-steps-filled': shapeStepsFilledIcon,
    'shape-steps-filled-mono': monoIcon(shapeStepsFilledIcon),
    'shape-steps': shapeStepsIcon,
    'shape-hourglass-filled-2': shapeHourglassFilled2Icon,
    'shape-hourglass-filled-mono-2': monoIcon(shapeHourglassFilled2Icon),
    'shape-hourglass-2': shapeHourglass2Icon,
    'shape-3d-abstract-filled-2': shape3dAbstractFilled2Icon,
    'shape-3d-abstract-filled-mono-2': monoIcon(shape3dAbstractFilled2Icon),
    'shape-3d-abstract-2': shape3dAbstract2Icon,
    'shape-diamond-filled-1': shapeDiamondFilled1Icon,
    'shape-diamond-filled-mono-1': monoIcon(shapeDiamondFilled1Icon),
    'shape-diamond-1': shapeDiamond1Icon,
    'shape-diamond-filled-2': shapeDiamondFilled2Icon,
    'shape-diamond-filled-mono-2': monoIcon(shapeDiamondFilled2Icon),
    'shape-diamond-2': shapeDiamond2Icon,
    'shape-dodecahedron-filled': shapeDodecahedronFilledIcon,
    'shape-dodecahedron-filled-mono': monoIcon(shapeDodecahedronFilledIcon),
    'shape-dodecahedron': shapeDodecahedronIcon,
    'shape-3d-plus-filled': shape3dPlusFilledIcon,
    'shape-3d-plus-filled-mono': monoIcon(shape3dPlusFilledIcon),
    'shape-3d-plus': shape3dPlusIcon,
    'shape-diamond-filled-3': shapeDiamondFilled3Icon,
    'shape-diamond-filled-mono-3': monoIcon(shapeDiamondFilled3Icon),
    'shape-diamond-3': shapeDiamond3Icon,
    'shape-cone-filled-2': shapeConeFilled2Icon,
    'shape-cone-filled-mono-2': monoIcon(shapeConeFilled2Icon),
    'shape-cone-2': shapeCone2Icon,
    'shape-3d-multiplication-filled': shape3dMultiplicationFilledIcon,
    'shape-3d-multiplication-filled-mono': monoIcon(shape3dMultiplicationFilledIcon),
    'shape-3d-multiplication': shape3dMultiplicationIcon,
    'shape-3d-abstract-filled-3': shape3dAbstractFilled3Icon,
    'shape-3d-abstract-filled-mono-3': monoIcon(shape3dAbstractFilled3Icon),
    'shape-3d-abstract-3': shape3dAbstract3Icon,
    'shape-sphere-skewed-filled': shapeSphereSkewedFilledIcon,
    'shape-sphere-skewed-filled-mono': monoIcon(shapeSphereSkewedFilledIcon),
    'shape-sphere-skewed': shapeSphereSkewedIcon,
    'shape-cylinder-skewed-filled': shapeCylinderSkewedFilledIcon,
    'shape-cylinder-skewed-filled-mono': monoIcon(shapeCylinderSkewedFilledIcon),
    'shape-cylinder-skewed': shapeCylinderSkewedIcon,
    'shape-horseshoe-filled-2': shapeHorseshoeFilled2Icon,
    'shape-horseshoe-filled-mono-2': monoIcon(shapeHorseshoeFilled2Icon),
    'shape-horseshoe-2': shapeHorseshoe2Icon,
    'shape-sphere-filled-2': shapeSphereFilled2Icon,
    'shape-sphere-filled-mono-2': monoIcon(shapeSphereFilled2Icon),
    'shape-sphere-2': shapeSphere2Icon,
    'shape-pyramid-filled-4': shapePyramidFilled4Icon,
    'shape-pyramid-filled-mono-4': monoIcon(shapePyramidFilled4Icon),
    'shape-pyramid-4': shapePyramid4Icon,
    'shape-pyramid-filled-5': shapePyramidFilled5Icon,
    'shape-pyramid-filled-mono-5': monoIcon(shapePyramidFilled5Icon),
    'shape-pyramid-5': shapePyramid5Icon,
    'shape-octahedron-transparent-filled': shapeOctahedronTransparentFilledIcon,
    'shape-octahedron-transparent-filled-mono': monoIcon(shapeOctahedronTransparentFilledIcon),
    'shape-octahedron-transparent': shapeOctahedronTransparentIcon,
    'shape-cube-transparent-filled': shapeCubeTransparentFilledIcon,
    'shape-cube-transparent-filled-mono': monoIcon(shapeCubeTransparentFilledIcon),
    'shape-cube-transparent': shapeCubeTransparentIcon,
    'shape-pyramid-transparent-filled': shapePyramidTransparentFilledIcon,
    'shape-pyramid-transparent-filled-mono': monoIcon(shapePyramidTransparentFilledIcon),
    'shape-pyramid-transparent': shapePyramidTransparentIcon,
    'shape-sphere-transparent-filled': shapeSphereTransparentFilledIcon,
    'shape-sphere-transparent-filled-mono': monoIcon(shapeSphereTransparentFilledIcon),
    'shape-sphere-transparent': shapeSphereTransparentIcon,
    'shape-cylinder-transparent-filled': shapeCylinderTransparentFilledIcon,
    'shape-cylinder-transparent-filled-mono': monoIcon(shapeCylinderTransparentFilledIcon),
    'shape-cylinder-transparent': shapeCylinderTransparentIcon,
    'shape-axes-cube-filled': shapeAxesCubeFilledIcon,
    'shape-axes-cube-filled-mono': monoIcon(shapeAxesCubeFilledIcon),
    'shape-axes-cube': shapeAxesCubeIcon,
    'shape-axes-pyramid-filled': shapeAxesPyramidFilledIcon,
    'shape-axes-pyramid-filled-mono': monoIcon(shapeAxesPyramidFilledIcon),
    'shape-axes-pyramid': shapeAxesPyramidIcon,
    'shape-axes-sphere-filled': shapeAxesSphereFilledIcon,
    'shape-axes-sphere-filled-mono': monoIcon(shapeAxesSphereFilledIcon),
    'shape-axes-sphere': shapeAxesSphereIcon,
    'shape-3d-shapes': shape3dShapesIcon,
    'shape-cube-cut-filled-2': shapeCubeCutFilled2Icon,
    'shape-cube-cut-filled-mono-2': monoIcon(shapeCubeCutFilled2Icon),
    'shape-cube-cut-2': shapeCubeCut2Icon,
    'shape-sphere-multi-filled': shapeSphereMultiFilledIcon,
    'shape-sphere-multi-filled-mono': monoIcon(shapeSphereMultiFilledIcon),
    'shape-sphere-multi': shapeSphereMultiIcon,
} as const
